# infrastructure/aws/cloudformation/stacks/staging/stack-config.yml

Description: 'Staging environment stack configuration for Layla App'

Parameters:
  Environment: staging

  # Network Configuration
  VPCId: vpc-stg123xyz
  PublicSubnet1Id: subnet-pub1stg123
  PublicSubnet2Id: subnet-pub2stg123
  PrivateSubnet1Id: subnet-priv1stg123
  PrivateSubnet2Id: subnet-priv2stg123
  VPCCidr: 10.1.0.0/16

  # S3 Configuration
  DataBucketName: layla-app-data-staging
  ModelsBucketName: layla-app-models-staging
  LogsBucketName: layla-app-logs-staging
  S3KMSKeyArn: arn:aws:kms:us-east-1:123456789012:key/staging-s3-key

  # RDS Configuration
  DBInstanceIdentifier: layla-app-db-staging
  DBSubnetGroupName: layla-app-db-subnet-group-staging
  DBSecurityGroupId: sg-dbstg123
  DBParameterGroupName: layla-app-db-pg-staging
  RDSKMSKeyArn: arn:aws:kms:us-east-1:123456789012:key/staging-rds-key
  DBInstanceClass: db.t3.large
  DBAllocatedStorage: 50
  MultiAZ: true

  # SageMaker Configuration
  NotebookInstanceName: layla-app-notebook-staging
  NotebookInstanceType: ml.t3.xlarge
  SageMakerEndpointName: layla-app-endpoint-staging
  ModelPackageGroupName: layla-app-models-staging
  DomainId: d-stg123xyz
  SageMakerKMSKeyArn: arn:aws:kms:us-east-1:123456789012:key/staging-sagemaker-key

  # ECR Configuration
  ECRRepositoryNames: 
    - layla-app-ml-model-staging
    - layla-app-feature-extractor-staging
    - layla-app-biomarker-processor-staging
    - layla-app-inference-api-staging
    - layla-app-data-processor-staging
  ECRKMSKeyArn: arn:aws:kms:us-east-1:123456789012:key/staging-ecr-key

  # Lambda Configuration
  LambdaFunctionNames:
    - layla-app-feature-processor-staging
    - layla-app-biomarker-analyzer-staging
    - layla-app-model-inference-staging
    - layla-app-data-preprocessor-staging
  LambdaKMSKeyArn: arn:aws:kms:us-east-1:123456789012:key/staging-lambda-key
  LambdaMemorySize: 2048
  LambdaTimeout: 600

  # Monitoring Configuration
  AlarmSNSTopicArn: arn:aws:sns:us-east-1:123456789012:layla-app-alarms-staging
  RetentionInDays: 30
  EnableDetailedMonitoring: true

Tags:
  Project: layla-app
  Environment: staging
  ManagedBy: cloudformation
  CostCenter: staging
  Version: 1.0.0
